name: GHAction Build test and push weather-app docker image to ghcr

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  ci_step:
    name: Build, tag, test and push Docker image to ghcr
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source_repo
        uses: actions/checkout@v4
        
      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/weather-app
          flavor: latest=true
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}
            
      - name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: local-weather-app:testscan
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/weather-app:cache
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/weather-app:cache,mode=max
          ssh: 'default'
      
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: local-weather-app:testscan
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'

     
      - name: Push image to GHCR (if scan passed)
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }}
            ghcr.io/${{ github.repository }}:latest
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/weather-app:cache
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/weather-app:cache,mode=max
          ssh: 'default'
